### PR TITLE
Fix and test key types

### LINKED ISSUE #128: Test all key types
https://github.com/Level/level-js/blob/c471684f704586cdb7201ec859f774fa281255ae/index.js#L114-L122

### PR DESCRIPTION
**Pull request by vweevers**
Closes #128, but doesn't test invalid types yet.

### CODE REVIEW

File: util/support.js [hunk 1]
```diff
@@ -1,19 +1,15 @@
...
 
-exports.arrayKeys = function (impl) {
-  try {
-    impl.cmp([1], 0)
-    return true
-  } catch (err) {
-    return false
-  }
-}
+exports.binaryKeys = exports.test(new Uint8Array(0))
```
Comment (ralphtheninja) [inline util/support.js]: Nice!
